---

- hosts: jenkins-host
  connection: local
  gather_facts: no

  vars:
    baseurl: http://mirror.sfo12.us.leaseweb.net/epel//7Server/x86_64/
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    secrets_bucket: accelerator-s3-secrets
    ssl_key_file: mycasebook.key
    ssl_crt_file: mycasebook.crt

  tasks:

  - name: Add EPEL repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: '{{ baseurl }}'
      gpgkey: '{{ gpgkey }}'
      gpgcheck: yes
    tags:
      - local_dependencies

  - name: install misc packages
    yum: name={{ item }} state=present
    with_items:
    - python-pip
    - vim
    - wget
    - curl
    tags:
      - local_dependencies

  - name: Install boto
    pip: name=boto state=present

  - name: Ensure tmp directory exists
    file: path=../tmp state=directory mode=777

  - name: Copy nginx.key to local
    s3:
      bucket: '{{ secrets_bucket }}'
      object: '{{ ssl_key_file }}'
      dest: '../tmp/nginx.key'
      mode: get

  - name: Copy nginx.crt to local
    s3:
      bucket: '{{ secrets_bucket }}'
      object: '{{ ssl_crt_file }}'
      dest: '../tmp/nginx.crt'
      mode: get

  - name: Copy datadog key to local
    s3:
      bucket: '{{ secrets_bucket }}'
      object: 'dd-agent.key'
      dest: '../tmp/dd-agent.key'
      mode: get

################################### intake
- hosts: intake-node
  connection: ssh
  user: ubuntu
  become: yes
  gather_facts: no

  vars:
    project_name: intake
    project_source: /home/ubuntu

  vars_prompt:
  - name: "username"
    prompt: "Enter docker username"
    private: no
  - name: "email"
    prompt: "Enter docker email"
    private: no
  - name: "password"
    prompt: "Enter docker password"
    private: yes

  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  
  - name: gather facts
    setup:

  - name: install misc packages
    apt: name={{ item }} state=present
    with_items:
    - python-pip
    - vim
    - wget
    - curl
    - telnet
    - rsyslog
    - rsyslog-elasticsearch

  roles:
  - { role: dochang.docker, docker_dockerpy_version: 1.10.6 }

  post_tasks:

  - name: Ensure presence of directory /var/lib/rsyslog
    file: name=/var/lib/rsyslog/ state=directory

  - name: Generate rsyslog conf
    template:
      src: ../shared/rsyslog.conf.j2
      dest: /etc/rsyslog.conf
    register: rsyslog_conf

  - name: Generate docker logging conf
    template:
      src: ../shared/99-docker.conf.j2
      dest: /etc/rsyslog.d/99-docker.conf
    register: rsyslog_logging_conf

  - name: Restart rsyslog
    service: name=rsyslog state=restarted
    when: rsyslog_conf.changed or rsyslog_logging_conf.changed

  - name: Ensure these users exists -- docker and deploy
    user: name={{ item }} group=docker state=present
    with_items:
    - docker
    - deploy
    - ubuntu

  - name: Install docker-compose 1.9.0 via python pip
    pip:
      name: docker-compose
      version: 1.9.0

  - name: Login to docker
    docker_login:
      username: '{{ username }}'
      email: '{{ email }}'
      password: '{{ password }}'

  - name: Create a docker network
    command: docker network create intake
    ignore_errors: True

  - include: deploy-docker-intake.yml
    vars:
      project_name: app
      ssl_key_file: nginx.key
      ssl_crt_file: nginx.crt
      ssl_path: /etc/nginx/ssl
      nginx_conf_fullpath: /etc/nginx/nginx.conf
      public_root: /ca_intake/public

  - name: Remove stopped containers older than a week
    shell: docker ps -a | awk '/Exited/ && /weeks ago/ {print "docker rm", $1}' | sh

  - name: Remove images of stopped containers except for those still in use
    shell: docker images -qa | { xargs -r docker rmi; echo; }

  - name: Remove dangling volumes
    shell: docker volume ls -qf dangling=true | xargs -r docker volume rm


- include: ../shared/add-datadog-agent.yml
  vars:
    hosts: intake-node
- include: ../shared/cleanup.yml
